orders/urls.py
from django.urls import path
from .views import OrderList , checkout, add_to_cart, CreateCheckoutSessionView, success_payment
from .api import OrderListApi, CartDetailApi, CreateOrder

app_name = 'orders'

urlpatterns = [
    path('', OrderList.as_view(),name='order_list'),
    path('checkout',checkout,name='checkout'),
    path('add-to-cart',add_to_cart,name='add_to_cart'),
    path('create_checkout_session/', CreateCheckoutSessionView.as_view(),name="create_checkout_session"),
    path("payment/success", success_payment),

    #api
    path('api/<str:username>/orders', OrderListApi.as_view()),
    path('api/<str:username>/orders-complete', CreateOrder.as_view()),
    path('api/<str:username>/carts', CartDetailApi.as_view()),

]

product/urls.py
from django.urls import path
from .views import ProductList, ProductDetail, add_review, BrandList, BrandDetail, Product_list_debug  , product_list_with_ajax
from .api import product_list_api, ProductListApi, ProductDetailAPI, BrandApi, BrandDetailApi
app_name = 'product'

urlpatterns = [
    path('', product_list_with_ajax, name='product_list2'),
    #path('', list, name='product_list2'),


    #api
    path('api/list',product_list_api, name='product_list'),
    path('api/list/cbv', ProductListApi.as_view()),
    path('api/list/cbv/brands', BrandApi.as_view()),
    path('api/list/cbv/brands/<slug:slug>', BrandDetailApi.as_view()),

    path('api/list/cbv/<slug:slug>', ProductDetailAPI.as_view()),


   # path('', ProductList.as_view(),name='product_list'),
    path('debug', Product_list_debug, name='product_list_debug'),

    path('<slug:slug>', ProductDetail.as_view(),name='product_detail'),
    path('<slug:slug>/add-review',add_review ,name='add_review'),
    path('brands/', BrandList.as_view(),name='brand_list'),
    path('brands/<slug:slug>',BrandDetail.as_view(), name='brand_detail' ),



]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from settings.views import home

urlpatterns = [
    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', home),
    path('admin/', admin.site.urls),
    path('products/',include('product.urls',namespace='products')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('__debug__/', include('debug_toolbar.urls')), 
    path('i18n/', include('django.conf.urls.i18n')),   

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.utils.translation import gettext as _
from django.utils.text import slugify

# Create your models here.
FLAG_TYPES = (
    ('New' , 'New'),
    ('Feature' , 'Feature'),
    ('Sale' , 'Sale'),
)



class Product(models.Model):
    name = models.CharField(_('name'),max_length=120)
    image = models.ImageField(_('image'),upload_to='products')
    price = models.FloatField(_('price'))
    sku = models.IntegerField(_('sku'))
    subtitle = models.CharField(_('subtitle'),max_length=300)
    description = models.TextField(_('description'),max_length=20000)
    flag = models.CharField(_('flag'),choices= FLAG_TYPES, max_length=10)
    brand = models.ForeignKey('Brand',related_name='product_brand' , on_delete=models.SET_NULL, null=True,blank=True, verbose_name=_('brand'))
    tags = TaggableManager()
    slug = models.SlugField(null=True, blank=True)    

    def __str__(self):
        return self.name

    def save(self,*args, **kwargs):
        self.slug = slugify(self.name)
        super(Product,self).save(*args,**kwargs)

    def avg_rate(self):
        product_reviews = self.product_review.all()
        if len(product_reviews)>0:
            review_sum = 0
            for rate in product_reviews:
                review_sum += rate.rate
            return round(review_sum/len(product_reviews),1)    
        else:
            return 0


class Brand(models.Model):
    name = models.CharField(_('name'),max_length=120)
    image = models.ImageField(_('image'),upload_to='brand')
    slug = models.SlugField(null=True, blank=True)    

    def __str__(self):
        return str(self.name)

    def save(self,*args, **kwargs):
        self.slug = slugify(self.name)
        super(Brand,self).save(*args,**kwargs)

class ProductReview(models.Model):
    user = models.ForeignKey(User,related_name='review_author',on_delete=models.SET_NULL, null=True,blank=True)
    product = models.ForeignKey(Product,related_name='product_review', on_delete=models.CASCADE)
    rate = models.IntegerField(_('rate'))
    review = models.TextField(_('review'),max_length=400) 
    data = models.DateTimeField(default=timezone.now)   

    def __str__(self):
        return str(self.user)

class ProductImages(models.Model):
    Product = models.ForeignKey(Product, related_name='product_images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='productimages')


    def __str__(self):
        return str(self.Product)

product/forms.py
from . models import ProductReview
from django import forms




class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = ['rate', 'review']

product/views.py
from django.http import JsonResponse
from django.shortcuts import render ,redirect
from django.views.generic import ListView,DetailView
from .models import Product, Brand
from .forms import ProductReviewForm
from django.db.models import Q , F
from django.db.models.aggregates import Avg, Sum, Count, Max 
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from django.template.loader import render_to_string
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.


@cache_page(60)
def Product_list_debug(request):

    '''
    - prefetch_related ------> many-to-many
    - select_related   ------> one-to-one     one-to-many

    '''
    #data = Product.objects.all().prefetch_related('brand')
    #data = Product.objects.filter(Q(price__gt=50) & Q(name__contains='avid'))    or & and operations
    #data = Product.objects.filter(sku =F('price'))   # compare two column

    #data = Product.objects.aggregate(Avg('price'))

    data = Product.objects.annotate(new_column=F('price')*1.5)  # add new column and do operations on it from another column


    return render(request, 'product/product_test.html', {'data':data})





def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH')=='XMLHttpRequest'


def product_list_with_ajax(request):
    product = Product.objects.all()
    all_count = Product.objects.all().count()
    print(all_count)
    if is_ajax(request=request):
        print('in ajax')
        min_price = request.GET['min_value']
        max_price = request.GET['max_value']
        queryset = Product.objects.filter(price__gt=min_price, price__lt=max_price)
        all_count = queryset.count()

    #----------------pagination------start------------------
        page_num = request.GET.get('page', 1)

        paginator = Paginator(queryset, 50) # 6 employees per page


        try:
            page_obj = paginator.page(page_num)
        except PageNotAnInteger:
            # if page is not an integer, deliver the first page
            page_obj = paginator.page(1)
        except EmptyPage:
            # if the page is out of range, deliver the last page
            page_obj = paginator.page(paginator.num_pages)



#----------------pagination------end------------------

        html = render_to_string('include/product_list_div.html',{'object_list':page_obj , request:request, 'all_count':all_count})
        return JsonResponse({'result':html})
    
    page_num = request.GET.get('page', 1)

    paginator = Paginator(product, 50) # 6 employees per page


    try:
        page_obj = paginator.page(page_num)
    except PageNotAnInteger:
        # if page is not an integer, deliver the first page
        page_obj = paginator.page(1)
    except EmptyPage:
        # if the page is out of range, deliver the last page
        page_obj = paginator.page(paginator.num_pages)



    # paginator = Paginator(product, 25)  # Show 25 contacts per page.

    # page_number = request.GET.get("page")
    # page_obj = paginator.get_page(page_number)



    return render(request,'product/product_list.html',{'object_list':page_obj ,'all_count':all_count})

class ProductList(ListView):
    model = Product
    paginate_by = 20

    extra_context = {'all_count': Product.objects.all().count()}
    
#------------------filtering by price  without ajax---------------
    def get_queryset(self):
        try:
            min_price = self.request.GET['min_value']
            max_price = self.request.GET['max_value']
            queryset = Product.objects.filter(price__gt=min_price, price__lt=max_price)
            return queryset
                
        except:    
            return super().get_queryset()
    



class ProductDetail(DetailView):
    model = Product   

    def get_context_data(self, **kwargs):
        product = self.get_object()
        context = super().get_context_data(**kwargs)
        context["related_products"] = Product.objects.filter(brand=product.brand)[:10]
        return context
     

def add_review(request,slug):
    product = Product.objects.get(slug = slug)
    if request.method == "POST":
        form = ProductReviewForm(request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.user = request.user
            myform.product = product
            myform.save()
    return redirect(f'/products/{product.slug}')        



class BrandList(ListView):
    model = Brand
    paginate_by = 50
    extra_context = {'add_count': Brand.objects.all().count()}




class BrandDetail(ListView):
    model = Product
    paginate_by = 50
    template_name = 'product/brand_detail.html'  

    #@method_decorator(cache_page(60))                      # use cache in cbv
    def get_queryset(self):
        brand = Brand.objects.get(slug=self.kwargs['slug'])
        queryset = Product.objects.filter(brand=brand)
        return queryset
      
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["brand"] = Brand.objects.get(slug=self.kwargs['slug'])
        return context
    

product/templates/product/brand_detail.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'en/css/brand-single.css' %}">
{% endblock css %}
{% block body %}
        <!--=====================================
                    PRODUCT VIEW END
        =======================================-->


        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>Brand Single</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="brand-list.html">brand-list</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-single</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                  BRAND SINGLE PART START
        =======================================-->
        <div class="brand-single">
            <a href="#"><img src="{{brand.image.url}}" alt="brand"></a>
            <a href="#"><h3>{{brand}}</h3></a>
            <ul>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star"></li>
                <li class="total">(163 ratings)</li>
            </ul>
            <p>({{brand.roduct_brand.all|length}} items)</p>
        </div>
        <!--=====================================
                  BRAND SINGLE PART END
        =======================================-->


        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                        </div>
                        <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4">
                            
                            {% for object in object_list  %}
                                
                            <div class="col">
                                <div class="product-card">
                                    <div class="product-media">
                                        <div class="product-label">
                                            <label class="label-text new">{{object.flag}}</label>
                                        </div>
                                        <button class="product-wish wish">
                                            <i class="fas fa-heart"></i>
                                        </button>
                                        <a class="product-image" href="product-video.html">
                                            <img src="{{object.image.url}}" alt="product">
                                        </a>
                                        <div class="product-widget">
                                            <a title="Product Compare" href="compare.html" class="fas fa-random"></a>
                                            <a title="Product Video" href="https://youtu.be/9xzcVxSBbG8" class="venobox fas fa-play" data-autoplay="true" data-vbtype="video"></a>
                                            <a title="Product View" href="#" class="fas fa-eye" data-bs-toggle="modal" data-bs-target="#product-view"></a>
                                        </div>
                                    </div>
                                    <div class="product-content">
                                        <div class="product-rating">
                                            <i class=" {% if object.avg_rate > 0 %} active {% endif %} icofont-star"></i>
                                            <i class=" {% if object.avg_rate > 1 %} active {% endif %} icofont-star"></i>
                                            <i class=" {% if object.avg_rate > 2 %} active {% endif %} icofont-star"></i>
                                            <i class=" {% if object.avg_rate > 3 %} active {% endif %} icofont-star"></i>
                                            <i class=" {% if object.avg_rate > 4 %} active {% endif %} icofont-star"></i>
                                            <a href="product-video.html">({{object.product_review.all|length}}) </a>
                                        </div>
                                        <h6 class="product-name">
                                            <a href="{% url 'products:product_detail' object.slug %}">{{object}}</a>
                                        </h6>
                                        <h6 class="product-price">
                                             
                                            <span>${{object.price}}<small></small></span>
                                        </h6>
                                        <button class="product-add" title="Add to Cart">
                                            <i class="fas fa-shopping-basket"></i>
                                            <span>add</span>
                                        </button>
                                        <div class="product-action">
                                            <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                            <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                            <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        {% if is_paginated %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="bottom-paginate">
                                    <p class="page-info">Showing 50 of {{all_count}} Results</p>
        
                                    <ul class="pagination">
                                        {% if page_obj.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                                    <i class="fas fa-long-arrow-alt-left"></i>
                                                </a>
                                            </li>
                                        {% else %}
                                            <li class="fas fa-long-arrow-alt-left disabled"></li>
                                        {% endif %}
        
                                        {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <li class="page-item"><a class="page-link active" href="#">{{ i }}</a></li>
        
                                            {% else %}
                                                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}
        
                                        {% if page_obj.has_next %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                                    <i class="fas fa-long-arrow-alt-right"></i>
                                                </a>
                                            </li>
                                        {% else %}
                                            <li class="fas fa-long-arrow-alt-right disabled"></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}
            </div>
        </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->
        
        {% endblock body %}

product/templates/product/brand_list.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'en/css/brand-list.css' %}">
{% endblock css %}
{% block body %}
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>brand list</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-list</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    BRAND LIST PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select isotope-select">
                                    <option value="*">show all</option>
                                    <option value=".vegetables">vegetables</option>
                                    <option value=".fruits">fruits</option>
                                    <option value=".drinks">drinks</option>
                                    <option value=".fishes">fishes</option>
                                    <option value=".meats">meats</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 isotope-items">
                    
                    {% for object in object_list  %}
                    <div class="col all vegetables">
                        <div class="brand-wrap">
                            <div class="brand-media">
                                <img src="{{object.image.url}}" alt="brand">
                                <div class="brand-overlay">
                                    <a href="{% url 'products:brand_detail' object.slug %}"><i class="fas fa-link"></i></a>
                                </div>
                            </div>
                            <div class="brand-meta">
                                <h4>{{object}}</h4>
                                <p>({{object.product_brand.all|length}} items)</p>
                            </div>
                        </div>
                    </div>   
                    {% endfor %}
                        

                </div>
                {% if is_paginated %}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 50 of {{all_count}} Results</p>

                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                            <i class="fas fa-long-arrow-alt-left"></i>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="fas fa-long-arrow-alt-left disabled"></li>
                                {% endif %}

                                {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item"><a class="page-link active" href="#">{{ i }}</a></li>

                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}

                                {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                            <i class="fas fa-long-arrow-alt-right"></i>
                                        </a>
                                    </li>
                                {% else %}
                                    <li class="fas fa-long-arrow-alt-right disabled"></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </section>
        <!--=====================================
                    BRAND LIST PART END
        =======================================-->

        {% endblock body %}

product/templates/product/product_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{data}}
    <ul>
        {% for object in data  %}
        <li>{{object}} - {{object.price}} - {{object.new_column}}</li>
        {% endfor %}
    </ul>  
    
</body>
</html>






  